yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import Pub_dateModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField('Имя группы', max_length=200)
    slug = models.SlugField('Ссылка', max_length=100, unique=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(Pub_dateModel):
    text = models.TextField('Пост', help_text='Чем хотите поделиться?')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='В какой группе разместим запись?'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Можете добавить изображение к посту'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(Pub_dateModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField('Комментарий',
                            help_text='Напишите ваш комментарий')

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='already_following'
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='revent_self_follow',
            ),
        ]

        def __str__(self) -> str:
            return f'Пользователь {self.user} надписан на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Пост',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Чем хотите поделиться?',
            'group': 'В какой группе разместим запись?',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Комментарий',
        }
        help_texts = {
            'text': 'Напишите ваш комментарий',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import page_context


def index(request):
    context = {
        'page_obj':
        page_context(request, Post.objects.select_related('author', 'group')
                     .all()),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
        'page_obj':
        page_context(request, group.posts.select_related('author')
                     .all()),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = author.following.filter(
        user=request.user.id,
    ).exists() and request.user.is_authenticated
    context = {
        'author': author,
        'page_obj':
        page_context(request, author.posts.select_related('group')
                     .all()),
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_detail = get_object_or_404(Post.objects.prefetch_related
                                    ('comments__author'), pk=post_id)
    form = CommentForm()
    context = {
        'post': post_detail,
        'comments': post_detail.comments.all(),
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user
    )
    context = {
        'page_obj': page_context(request, post_list),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(Follow, author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
    {% block title %}
      {% if form.instance.pk %}Редактирование поста{% else %}Новый пост{% endif %}   
    {% endblock %}
    {% block content %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if form.instance.pk %}Редактировать{% else %}Новый пост{% endif %} 
            </div>
            <div class="card-body"> 
              {% include 'includes/form_errors.html' %}   
              <form method="post" enctype="multipart/form-data"
              {% if form.instance.pk %} 
                action="{% url 'posts:post_edit' form.instance.pk %}" 
              {% else %} 
                action="{% url 'posts:post_create' %}"
              {% endif %}>
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  {% include 'includes/field_in_form.html' %}
                  <button type="submit" class="btn btn-primary">
                    {% if form.instance.pk %}Сохранить{% else %}Добавить{% endif %}               
                  </button> 
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endblock content %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
    {% block title %}Моя лента{%endblock %}
    {% block content %}
      <div class="container py-5">
        {% include 'posts/includes/switcher.html' %}
        <h1>Моя лента</h1>
        {% for post in page_obj %}
          {% include 'posts/includes/post_card.html' %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
    {% block title %}Записи сообщества {{ group }}{% endblock %}
    {% block content %}
      <div class="container py-5">
        <h1>{{ group }}</h1>
        <h3>{{ group.description|linebreaks  }}</h3>
        {% for post in page_obj %}
          {% include 'posts/includes/post_card.html' %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
      </div> 
    {% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
    {% block title %}Последние обновления на сайте{%endblock %}
    {% block content %}
      <div class="container py-5">
        {% include 'posts/includes/switcher.html' %}
        <h1>Последние обновления на сайте</h1>
        {% cache 30 sidebar index page_obj.number %}
        {% for post in page_obj %}
          {% include 'posts/includes/post_card.html' %}
        {% endfor %}
        {% endcache %} 
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост: {{ post.text|truncatechars:30 }}{%endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        <li class="list-group-item">
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
          {% else %} <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post.author.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      {% if user.username == post.author.username %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>   
      {% endif %}
      {% include 'posts/includes/comments.html' %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author }} </h1>
    <h4>Всего постов: {{ author.posts.count }} </h4>
    <h5>Подписчики: {{ author.following.count }} </h5>
    <h5>Подписки: {{ author.follower.count }} </h5>
    {% if request.user != author and user.is_authenticated %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %} 